# Generated by Django 3.2.8 on 2021-11-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_report_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_recent',
            field=models.BooleanField(default=False),
        ),
    ]
