# Generated by Django 3.0.7 on 2021-11-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_report_is_recent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pahoto1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pahoto2',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
