# Generated by Django 3.0.7 on 2021-11-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211115_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pahoto1',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pahoto2',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
