# Generated by Django 3.2.8 on 2021-11-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211115_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='activity',
            field=models.CharField(blank=True, choices=[('Spiritual', 'Spiritual'), ('Educational', 'Educational'), ('Service', 'Service')], max_length=50),
        ),
    ]
