# Generated by Django 3.2.8 on 2021-11-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_report_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='activity',
            new_name='wings',
        ),
    ]
