# Generated by Django 3.2.8 on 2021-11-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_activity_report_wings'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
