# Generated by Django 3.2.8 on 2021-11-17 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_report_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='image',
        ),
    ]
