# Generated by Django 3.2.8 on 2021-11-17 17:53

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0010_remove_report_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('samthi', models.CharField(blank=True, choices=[('Ameerpet', 'Ameerpet'), ('Amberpet', 'Amberpet'), ('Dilsukhnagar', 'Dilsukhnagar'), ('Gandhinagar', 'Gandhinagar'), ('Himayathnagar', 'Himayathnagar'), ('Kachiguda', 'Kachiguda'), ('Khairtabad', 'Khairtabad'), ('Koti', 'Koti'), ('Mehdipatnam', 'Mehdipatnam'), ('Marredpally', 'Marredpally'), ('Prasanthi Nagar', 'Prasanthi Nagar'), ('Seethaphalmandi', 'Seethaphalmandi'), ('S R Nagar', 'S R Nagar'), ('Tarnaka', 'Tarnaka'), ('Vengal Rao Nagar', 'Vengal Rao Nagar'), ('Vidya Nagar', 'Vidya Nagar')], max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='pahoto1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pahoto2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
