# Generated by Django 3.2.8 on 2021-11-17 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_auto_20211117_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samathi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samthi', models.CharField(blank=True, choices=[('Ameerpet', 'Ameerpet'), ('Amberpet', 'Amberpet'), ('Dilsukhnagar', 'Dilsukhnagar'), ('Gandhinagar', 'Gandhinagar'), ('Himayathnagar', 'Himayathnagar'), ('Kachiguda', 'Kachiguda'), ('Khairtabad', 'Khairtabad'), ('Koti', 'Koti'), ('Mehdipatnam', 'Mehdipatnam'), ('Marredpally', 'Marredpally'), ('Prasanthi Nagar', 'Prasanthi Nagar'), ('Seethaphalmandi', 'Seethaphalmandi'), ('S R Nagar', 'S R Nagar'), ('Tarnaka', 'Tarnaka'), ('Vengal Rao Nagar', 'Vengal Rao Nagar'), ('Vidya Nagar', 'Vidya Nagar')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
