# Generated by Django 3.2.8 on 2022-03-14 10:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_report_aname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='form_time',
            new_name='from_time',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='aname',
            new_name='name_of_the_activity',
        ),
        migrations.AlterField(
            model_name='report',
            name='educational_activity',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Balvikas', 'Balvikas'), ('Gems', 'Gems'), ('Goodparenting', 'Goodparenting')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='service_activity',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Narayanaseva', 'Narayanaseva'), ('Medicalcamp', 'Medicalcamp'), ('Veterinarycamp', 'Veterinarycamp'), ('Educational_assistance', 'Educational_assistance'), ('vocational_Training', 'Vocational_Training'), ('Skill_Development', 'Skill_Development'), ('hospital_seva', 'hospital_seva'), ('Oldage_home', 'Oldage_home'), ('Gramaseva', 'Gramaseva'), ('Providing_relief', 'Providing_relief')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='spiritual_activity',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Bhajan', 'Bhajan'), ('Nagarsankeertan', 'Nagarsankeertan'), ('Studycircle', 'Studycircle'), ('Namasmarana', 'Namasmarana'), ('Japa', 'Japa'), ('Meditation', 'Meditation'), ('Spiritualclass', 'Spiritualclass'), ('Lectures', 'Lectures'), ('Seminars', 'Seminars'), ('Sadhanacamps', 'Sadhanacamps')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='wings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Spiritual', 'Spiritual'), ('Educational', 'Educational'), ('Service', 'Service')], max_length=50),
        ),
    ]
