# Generated by Django 3.2.8 on 2022-03-16 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220315_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_activity',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='from_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='to_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
