# Generated by Django 3.2.8 on 2022-03-19 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_dist_office_bearers_samithi_office_bearers_sivam_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='sivam_events',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
