# Generated by Django 3.2.8 on 2022-03-20 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_about_hnr_samithi'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_hnr_samithi',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
