# Generated by Django 3.2.8 on 2022-03-20 17:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_carousel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_sivam', ckeditor.fields.RichTextField()),
                ('wings', ckeditor.fields.RichTextField()),
                ('s_photo1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('sw_heading', models.CharField(max_length=150)),
                ('sw_para', models.CharField(max_length=150)),
                ('e_photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('ew_heading', models.CharField(max_length=150)),
                ('ew_para', models.CharField(max_length=150)),
                ('s_photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('swg_heading', models.CharField(max_length=150)),
                ('swg_para', models.CharField(max_length=150)),
            ],
        ),
    ]
