# Generated by Django 3.2.8 on 2022-03-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_amberpet_samithi_amberpet_samithi_report_amberpet_signin_amberpet_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amberpet_signup',
            name='user',
        ),
        migrations.DeleteModel(
            name='amberpet_signin',
        ),
        migrations.DeleteModel(
            name='amberpet_signup',
        ),
    ]
