# Generated by Django 3.2.8 on 2022-03-23 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20220323_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='as_office_bearers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True, max_length=150)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='amberpet_samithi',
            name='address',
        ),
        migrations.RemoveField(
            model_name='amberpet_samithi',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='amberpet_samithi',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='amberpet_samithi',
            name='email',
        ),
        migrations.RemoveField(
            model_name='amberpet_samithi',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='amberpet_samithi',
            name='name',
        ),
    ]
