# Generated by Django 3.2.8 on 2022-03-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_contact_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sivam_about_page',
            name='sivam_img',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
