# Generated by Django 3.2.8 on 2022-03-25 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_sivam_ew_page_sivam_spw_page_sivam_srw_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samathi',
            name='samthi',
        ),
        migrations.RemoveField(
            model_name='samathi',
            name='user',
        ),
        migrations.AddField(
            model_name='amberpet_samithi',
            name='samithi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.samathi'),
        ),
        migrations.AddField(
            model_name='amberpet_samithi_report',
            name='samithi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.samathi'),
        ),
        migrations.AddField(
            model_name='as_office_bearers',
            name='samithi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.samathi'),
        ),
        migrations.AddField(
            model_name='samathi',
            name='Amberpet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='samathi',
            name='Ameerpet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='samathi',
            name='Dilsuknagar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='samathi',
            name='Gandhinagar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='samathi',
            name='Himayathnagar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='samathi',
            name='Kachiguda',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='samathi',
            name='Khartabad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='samathi',
            name='Koti',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='samathi',
            name='Marredpally',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='samathi',
            name='Mehdipatnam',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='samathi',
            name='Prasanthnagar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='samathi',
            name='SRnagar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='samathi',
            name='Sitaphalmandi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='samathi',
            name='Tarnaka',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='samathi',
            name='Vengalraonagar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='samathi',
            name='Vidyanagar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='samithi_office_bearers',
            name='samithi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.samathi'),
        ),
    ]
