# Generated by Django 3.2.8 on 2022-03-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20220325_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='amberpet_samithi_report',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
