# Generated by Django 3.2.8 on 2022-03-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_signup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='samithi_login',
            name='title',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
